version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # merged and released instantly
      sec-updates:
        applies-to: security-updates
        patterns:
          - "*"
      # merged automatically
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      # merged and released instantly
      sec-updates:
        applies-to: security-updates
        patterns:
          - "*"
      # merged automatically
      dev-dependencies:
        patterns:
          # gradle plugins
          - "*kotlin-gradle-plugin"
          - "*publish-plugin"
          # test dependencies
          - "org.spockframework*"
          - "ch.qos.logback*"
          - "*jsonassert"
      # merged and released automatically
      prod-dependencies:
        update-types:
          - "patch"
          - "minor"
      # requires human approval and has higher chance to fail build
      prod-dependencies-major:
        update-types:
          - "major"