[versions]
# build tools
java = "17"
jacoco = "0.8.8"
kotlin = "1.8.10"

[libraries]
# build tools
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.1.0" }
# dependencies
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.0.0" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "1.33" }
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
# test dependencies
spock-core = { module = "org.spockframework:spock-core", version = "2.3-groovy-4.0" }
jsonassert = { module = "org.skyscreamer:jsonassert", version = "1.5.1" }