package com.coditory.quark.config;

import java.math.BigDecimal;
import java.time.Duration;
import java.time.Instant;
import java.time.ZonedDateTime;
import java.util.Currency;
import java.util.Locale;
import java.util.Optional;

import static com.coditory.quark.config.MissingConfigValueException.missingConfigValueForPath;

interface ConfigGetters {
    <T> Optional<T> getAsOptional(Class<T> type, String path);

    default <T> T getAs(Class<T> type, String path) {
        return getAsOptional(type, path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default <T> T getAsOrNull(Class<T> type, String path) {
        return getAs(type, path, null);
    }

    default <T> T getAs(Class<T> type, String path, T defaultValue) {
        return getAsOptional(type, path).orElse(defaultValue);
    }

    // generated by: generateConfigGetters.sh
    // GETTERS

    // String API

    default Optional<String> getStringOptional(String path) {
        return getAsOptional(String.class, path);
    }

    default String getString(String path) {
        return getStringOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default String getStringOrNull(String path) {
        return getString(path, null);
    }

    default String getString(String path, String defaultValue) {
        return getStringOptional(path).orElse(defaultValue);
    }

    // Object API

    default Optional<Object> getObjectOptional(String path) {
        return getAsOptional(Object.class, path);
    }

    default Object getObject(String path) {
        return getObjectOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Object getObjectOrNull(String path) {
        return getObject(path, null);
    }

    default Object getObject(String path, Object defaultValue) {
        return getObjectOptional(path).orElse(defaultValue);
    }

    // Boolean API

    default Optional<Boolean> getBooleanOptional(String path) {
        return getAsOptional(Boolean.class, path);
    }

    default Boolean getBoolean(String path) {
        return getBooleanOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Boolean getBooleanOrNull(String path) {
        return getBoolean(path, null);
    }

    default Boolean getBoolean(String path, Boolean defaultValue) {
        return getBooleanOptional(path).orElse(defaultValue);
    }

    // Short API

    default Optional<Short> getShortOptional(String path) {
        return getAsOptional(Short.class, path);
    }

    default Short getShort(String path) {
        return getShortOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Short getShortOrNull(String path) {
        return getShort(path, null);
    }

    default Short getShort(String path, Short defaultValue) {
        return getShortOptional(path).orElse(defaultValue);
    }

    // Byte API

    default Optional<Byte> getByteOptional(String path) {
        return getAsOptional(Byte.class, path);
    }

    default Byte getByte(String path) {
        return getByteOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Byte getByteOrNull(String path) {
        return getByte(path, null);
    }

    default Byte getByte(String path, Byte defaultValue) {
        return getByteOptional(path).orElse(defaultValue);
    }

    // Integer API

    default Optional<Integer> getIntegerOptional(String path) {
        return getAsOptional(Integer.class, path);
    }

    default Integer getInteger(String path) {
        return getIntegerOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Integer getIntegerOrNull(String path) {
        return getInteger(path, null);
    }

    default Integer getInteger(String path, Integer defaultValue) {
        return getIntegerOptional(path).orElse(defaultValue);
    }

    // Long API

    default Optional<Long> getLongOptional(String path) {
        return getAsOptional(Long.class, path);
    }

    default Long getLong(String path) {
        return getLongOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Long getLongOrNull(String path) {
        return getLong(path, null);
    }

    default Long getLong(String path, Long defaultValue) {
        return getLongOptional(path).orElse(defaultValue);
    }

    // Float API

    default Optional<Float> getFloatOptional(String path) {
        return getAsOptional(Float.class, path);
    }

    default Float getFloat(String path) {
        return getFloatOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Float getFloatOrNull(String path) {
        return getFloat(path, null);
    }

    default Float getFloat(String path, Float defaultValue) {
        return getFloatOptional(path).orElse(defaultValue);
    }

    // Double API

    default Optional<Double> getDoubleOptional(String path) {
        return getAsOptional(Double.class, path);
    }

    default Double getDouble(String path) {
        return getDoubleOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Double getDoubleOrNull(String path) {
        return getDouble(path, null);
    }

    default Double getDouble(String path, Double defaultValue) {
        return getDoubleOptional(path).orElse(defaultValue);
    }

    // BigDecimal API

    default Optional<BigDecimal> getBigDecimalOptional(String path) {
        return getAsOptional(BigDecimal.class, path);
    }

    default BigDecimal getBigDecimal(String path) {
        return getBigDecimalOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default BigDecimal getBigDecimalOrNull(String path) {
        return getBigDecimal(path, null);
    }

    default BigDecimal getBigDecimal(String path, BigDecimal defaultValue) {
        return getBigDecimalOptional(path).orElse(defaultValue);
    }

    // Instant API

    default Optional<Instant> getInstantOptional(String path) {
        return getAsOptional(Instant.class, path);
    }

    default Instant getInstant(String path) {
        return getInstantOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Instant getInstantOrNull(String path) {
        return getInstant(path, null);
    }

    default Instant getInstant(String path, Instant defaultValue) {
        return getInstantOptional(path).orElse(defaultValue);
    }

    // ZonedDateTime API

    default Optional<ZonedDateTime> getZonedDateTimeOptional(String path) {
        return getAsOptional(ZonedDateTime.class, path);
    }

    default ZonedDateTime getZonedDateTime(String path) {
        return getZonedDateTimeOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default ZonedDateTime getZonedDateTimeOrNull(String path) {
        return getZonedDateTime(path, null);
    }

    default ZonedDateTime getZonedDateTime(String path, ZonedDateTime defaultValue) {
        return getZonedDateTimeOptional(path).orElse(defaultValue);
    }

    // Duration API

    default Optional<Duration> getDurationOptional(String path) {
        return getAsOptional(Duration.class, path);
    }

    default Duration getDuration(String path) {
        return getDurationOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Duration getDurationOrNull(String path) {
        return getDuration(path, null);
    }

    default Duration getDuration(String path, Duration defaultValue) {
        return getDurationOptional(path).orElse(defaultValue);
    }

    // Locale API

    default Optional<Locale> getLocaleOptional(String path) {
        return getAsOptional(Locale.class, path);
    }

    default Locale getLocale(String path) {
        return getLocaleOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Locale getLocaleOrNull(String path) {
        return getLocale(path, null);
    }

    default Locale getLocale(String path, Locale defaultValue) {
        return getLocaleOptional(path).orElse(defaultValue);
    }

    // Currency API

    default Optional<Currency> getCurrencyOptional(String path) {
        return getAsOptional(Currency.class, path);
    }

    default Currency getCurrency(String path) {
        return getCurrencyOptional(path)
                .orElseThrow(() -> missingConfigValueForPath(path));
    }

    default Currency getCurrencyOrNull(String path) {
        return getCurrency(path, null);
    }

    default Currency getCurrency(String path, Currency defaultValue) {
        return getCurrencyOptional(path).orElse(defaultValue);
    }

}

