name: Build

on: [pull_request, push, workflow_dispatch]

jobs:
  deduplicate:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip.outputs.should_skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Skip duplicates and docs
        id: skip
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer
          paths_ignore: '["**/README.md", "LICENSE", ".gitignore", ".editorconfig", ".idea/**"]'

  build:
    runs-on: ubuntu-latest
    needs: deduplicate
    if: "needs.pre_job.outputs.should_skip != 'true'"
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          cache: gradle
          distribution: temurin

      - name: Build with gradle
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew build
